import type { Metadata } from "next";
import { Lora, Pacifico } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import Header from "@/components/header";
import { Language } from "@/components/header/languageSelect";
import { Country } from "@/components/header/countrySelect";
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
})
const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fetchAvailableCountries = async (): Promise<Country[]> => {
    const response = await fetch('http://de1.api.radio-browser.info/json/countries', {
      cache: 'force-cache'
    })
    if (!response.ok) {
      throw new Error('Failed to fetch available countries')
    }
    return response.json() as Promise<Country[]>
  }
  const fetchAvailableLanguages = async (): Promise<Language[]> => {
    const response = await fetch('http://de1.api.radio-browser.info/json/languages', {
      cache: 'force-cache'
    })
    if (!response.ok) {
      throw new Error('Failed to fetch available languages')
    }
    return response.json() as Promise<Language[]>
  }
  const availableCountries = fetchAvailableCountries()
  const availableLanguages = fetchAvailableLanguages()
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${pacifico.variable} antialiased`}
      >
        <div className="flex h-screen">
          <SideBar />
          <div className="flex-1">
            <Header availableCountries={availableCountries} availableLanguages={availableLanguages} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
